### ISSUE TITLE
Skip landsat scenes ending in _RT?

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/its-live-monitoring#16]
These "real time" products are reprocessed and replaced a week or two after aquisition.

See "Collection 2 Tiers" at https://www.usgs.gov/landsat-missions/landsat-collection-2-level-1-data

**Comment by jhkennedy** [comment]
Correct, we do not want to process the real-time scenes:
https://itslive.slack.com/archives/CA1B96EU8/p1709764297467159?thread_ts=1709764200.031259&cid=CA1B96EU8
