### ISSUE TITLE
log.debug statements fail to print the pair list

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/its-live-monitoring#20]
Nothing is emitted by by the two log.debug statements in `process_scene()` at https://github.com/ASFHyP3/its-live-monitoring/blob/develop/landsat/src/main.py#L177 , even when the log level is set to DEBUG.

**Comment by jhkennedy** [comment]
:thinking: interesting -- it prints for me when using using it locally on the CLI

**Comment by asjohnston-asf** [comment]
From the current `develop` commit (f8c6ad99ce1998321f96d7635d4963962ac8e0f1):

![Screenshot from 2024-03-06 15-25-04](https://github.com/ASFHyP3/its-live-monitoring/assets/17994518/3689451c-414f-40db-b481-326d433dbbfa)
