### ISSUE TITLE
alert operators when SQS messages fail to be processed

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/its-live-monitoring#22]
We only attempt to process each SQS message a certain number of times before it is sent to the dead letter queue, as specified at https://github.com/ASFHyP3/its-live-monitoring/blob/develop/landsat/cloudformation.yml#L29

Any messages that end up in the dead letter queue will require manual review and will disappear after 14 days. Operators should receive some kind of push notification whenever any messages are available in the DLQ that require review.

That's probably a cloudwatch alarm on the number of messages in the DLQ plus an SNS email subscription, similar to HyP3's monitoring alarm: https://github.com/ASFHyP3/hyp3/blob/develop/apps/monitoring-cf.yml.j2

**Comment by jhkennedy** [comment]
Done in #53
