### ISSUE TITLE
Handle Off-nadir scenes

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/its-live-monitoring#9]
In the intial ITS_LIVE pair picking scripts, off-nadir scenes have special handling
* https://github.com/nasa-jpl/its_live_production/blob/main/src/tools/missingpairstools/operational_USGS_L89_findmissingpairs_v0.py
* https://github.com/nasa-jpl/its_live_production/blob/main/src/tools/missingpairstools/find_all_USGS_Collection2_imagepairs_for_jsoncatalogs.py

 and right now, we restrict to only processing nadir scenes.

We should follow the methods in the script to enable processing of off-nadir scenes.

**Comment by asjohnston-asf** [comment]
I'll need a summary of the strategy for off-nadir scenes, I haven't been able to appreciate it from just those code samples.

If the strategy is "only pair off-nadir scenes with similarly off-nadir scenes", that could be implemented by removing the nadir=0 requirement in [_qualifies_for_processing()](https://github.com/ASFHyP3/its-live-monitoring/blob/develop/landsat/src/main.py#L45), and updating the [secondary query](https://github.com/ASFHyP3/its-live-monitoring/blob/develop/landsat/src/main.py#L75) to only return items matching the reference nadir value.

**Comment by jhkennedy** [comment]
Done in #56
